import { tool } from "@langchain/core/tools";
import { z } from "zod";

export const generateReport = tool(
  async (args) => {
    const {
      contractAddress,
      socialData,
      marketData,
      onChainData,
      socialAnalysis,
      marketAnalysis,
      onChainAnalysis,
      opportunityEvaluation,
    } = args;

    return `
# Contract Analysis Report for ${contractAddress}

## Executive Summary

${opportunityEvaluation.split("OVERALL ASSESSMENT:")[1].split("\n\n")[0].trim()}

## Raw Data

### Social Data (Farcaster)
\`\`\`
${socialData.trim()}
\`\`\`

### Market Data (Coingecko)
\`\`\`
${marketData.trim()}
\`\`\`

### On-Chain Data (Etherscan)
\`\`\`
${onChainData.trim()}
\`\`\`

## Expert Analysis

### Social Sentiment Analysis
${socialAnalysis.trim()}

### Market Analysis
${marketAnalysis.trim()}

### On-Chain Analysis
${onChainAnalysis.trim()}

## Opportunity Assessment

${opportunityEvaluation.trim()}

## Disclaimer
This report is generated by AI agents and should not be considered financial advice.
All investments carry risk, and independent research is always recommended.

Report generated: ${new Date().toISOString()}
    `;
  },
  {
    name: "generate_report",
    description: "Generate a comprehensive markdown report of all findings.",
    schema: z.object({
      contractAddress: z.string(),
      socialData: z.string(),
      marketData: z.string(),
      onChainData: z.string(),
      socialAnalysis: z.string(),
      marketAnalysis: z.string(),
      onChainAnalysis: z.string(),
      opportunityEvaluation: z.string(),
    }),
  }
);
